version: '3'

services:
  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: nduta2
      DB_USERNAME: nduta
      DB_PASSWORD: nduta###2014

  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Luaitech###2014
      MYSQL_DATABASE: nduta2
      MYSQL_USER: nduta
      MYSQL_PASSWORD: nduta###2014
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db
    volumes:
      - ./config.user.inc.php:/etc/phpmyadmin/config.user.inc.php

volumes:
  db_data:
